### ISSUE TITLE
What is the behaviour of the Driver when Secret is updated

### ISSUE THREAD

**Issue by gauravAggrahari** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1026]
Hi,
What would be the expected behaviour of the driver when I update the secret. 
Do I need to restart the `Dayployment` and `Daemonset` or the changes would be taken dynamically ?

Regards,
Gaurav

**Comment by mattcary** [comment]
https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically

Since the controller mounts it as a volume, it should work without needing to update the controller? We don't specifically test this scenario, though, so you may need to experiment.

As long as you're not changing the SA in the secret (ie, you're just updating the token), I don't think it would cause problems.

Changing the SA obviously could prevent access to pre-existing volumes so you'll have to be careful in any case.

The daemonset doesn't use the secret (it doesn't talk to the GCP api), so nothing will be needed there in any case.

/close
