### ISSUE TITLE
read only volumes should not be expanded and we need OSS ROX testing

### ISSUE THREAD

**Issue by leiyiz** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1088]
#972 added unconditional filesystem resize and it should not happen for read only volumes. We are not seeing failures in mounting as resizing RO volume only produce an warning but this could have broken ROX functionality.

1. we should not try to expand RO volumes
2. we should write an OSS ROX test ASAP

**Comment by mattcary** [comment]
To clarify, it is the filesystem resize that's the problem, not the volume resize?

**Comment by judemars** [comment]
I'll pick this up, can someone who's a contributor please assign it to me :)

**Comment by leiyiz** [comment]
> To clarify, it is the filesystem resize that's the problem, not the volume resize?

yes, I'll update the issue description

**Comment by judemars** [comment]
Just a progress update. I think this work will have a few parts:

1) Update [mount-utils' resizefs_linux](https://github.com/kubernetes/mount-utils/blob/master/resizefs_linux.go) to add a check for readonly bit of filesystem to NeedResize method and return false if so, like [so (I made the change directly in the pd repo so you'll have to expand the diff)](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/compare/master...judemars:gcp-compute-persistent-disk-csi-driver:skip-readonly#diff-5f93e3e44b5ce809b3f2c74a8eb81137e147753090923dca79142a9c23380d22)
2) Update mount-utils package version in pd repo to consume #1 + update resize NodeStageVolume UTs to test resize is skipped if volume is readonly
3) Add ROX k8s integration tests for snapshot, clone, and restore cases. Snapshot and clone will also test that resize is skipped for ROX mode.

I have a couple outstanding questions I'm working through so posting here in case folks have any insight:
1) Updating resizefs in mount_utils will mean that the call to resize in NodeExpandVolume will also be skipped since it calls the same method. Is this okay? It seems like it would have to be since the resize will fail if it's readonly anyways. But as another follow up to that: what happens if the request to NodeExpandVolume has VolumeCapability set to *READER_ONLY? Should we also skip resize in that case?

2) Do we need to update the resize code for windows as well as linux? According to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/972#issuecomment-1263814191 it goes through a CSI proxy for the resize instead of doing it directly, but I currently can't find the implementation to be able to check.

**Comment by judemars** [comment]
go/k8spr/114628 out for review

**Comment by judemars** [comment]
For 2) it looks like I need to make a change like https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1025 to update the version of k8s to 1.27 - @leiyiz (since you did that CL) are we scheduled to upgrade it on some cadence or should I manually do it now?
