### ISSUE TITLE
CreateVolume call failing on trying to find the disk

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#144]
First pvc got provisioned alright but second one is stuck on:

```
{"log":"E1030 16:47:30.481739       1 utils.go:55] GRPC error: rpc error: code = Internal desc = CreateVolume unknown get disk error when validating: context canceled\n","stream":"stderr","time":"2018-10-30T16:47:30.482182878Z"}
```

This is when code is trying to fetch the disk to verify if the disk already exists.   I am not sure what is causing the context to be cancelled. The overall pod is failing because of snapshot controller not able to start, but I am not sure if this is related to that.

cc @msau42

**Comment by msau42** [comment]
Does it still fail after retry?  I know sometimes the timeout set in the context is too short and it might take a few retries before the operation succeeds.

cc @davidz627

**Comment by gnufied** [comment]
It eventually worked but it kept failing for more than 40 minutes.

**Comment by davidz627** [comment]
@gnufied for a quick fix you could you try setting the `--connection-timeout` flag to a greater value on the external-provisioner?
It looks like the default is 10 seconds but maybe that is too short. Although I don't expect the `CreateVolume` call to take more than 10 seconds assuming the cloud provider is responding at normal speeds, especially since up to the line number you linked only 1 cloud provider call is being made prior - `gceCS.CloudProvider.ListZones(context.Background(), region` - although it does seem like this call is not using the same context and should be fixed (though it shouldn't affect the issue you're seeing here).

I have not been able to reproduce this error, could you confirm it's still happening and if it is under any special circumstances? Do you have the link to test flake mentioned https://github.com/kubernetes/kubernetes/pull/68025#issuecomment-434425149?

**Comment by gnufied** [comment]
for example:

```
• Failure in Spec Setup (BeforeEach) [329.516 seconds]
[sig-storage] CSI Volumes
/home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:22
  [Driver: com.google.csi.gcepd][Serial]
  /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:80
    [Testpattern: Dynamic PV (ext4)] volumes
    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:111
      should be mountable [BeforeEach]
      /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:151

      Expected error:
          <*errors.errorString | 0xc001a58840>: {
              s: "PersistentVolumeClaim pvc-pw2pz not in phase Bound within 5m0s",
          }
          PersistentVolumeClaim pvc-pw2pz not in phase Bound within 5m0s
      not to have occurred

      /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:282
------------------------------
```

I will try and increase the timeout. Essentially, I am not doing anything special. I brought up a gce-cluster using ./kube-up.sh and then both while manually deploying the gce-csi driver and gce-csi driver deployed by e2e, I am seeing context being cancelled all over the place.

**Comment by gnufied** [comment]
I increased the timeout to 60s just for kicks and the flakes were almost gone.

**Comment by msau42** [comment]
This could potentially indicates there's an issue in the pd driver when handling timed out operations and retries

**Comment by msau42** [comment]
/remove-lifecycle stale
/lifecycle frozen

We should test and make sure the PD driver can handle timed out operations being retried correctly.

The latest sidecars also have new operation timeout parameters that we can tune for our operations

**Comment by davidz627** [comment]
Unable to reproduce.

IF you set the timeout on the `external-provisioner` super low it will continuously call `CreateVolume` and cancel the context never completing the volume creation. Unless more evidence appears otherwise I am going to assume that GCP was being slow the day this issue appeared and caused cloud provider calls to be slower than usual causing repeated timeouts.

/close
