### ISSUE TITLE
Driver should check socket parent directory before trying to bind it

### ISSUE THREAD

**Issue by jingxu97** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#222]
While testing the driver, we found that in the server's code https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/server.go#L85,  if the socket parent directory does not exit, the driver does not check it and just tries to call Listen to the address. So the error message returned from Listen call does not give the clear reason why it fail. It would be better to check whether the parent directory exist or not before listening to the socket address.

**Comment by hantaowang** [comment]
The error output should be:

    listen unix /path/to/sock/csi.sock: bind: no such file or directory

if /path/to/sock does not exist. Is that not a clear enough error?

**Comment by zhucan** [comment]
why remove the addr before listen to it ?

**Comment by davidz627** [comment]
> I'm wondering it would be better to do a mkdirall rather than reject it.

I believe we don't want to do this is because the driver expects `Kubelet` to create the parent directory for plugin registration. If the directory does not exist that is actually indicative of some sort of issue so we don't want to just mask the issue, drop the socket, and have the Kubelet potentially do nothing with it. Instead I think the idea is to just throw an error that contains more information such as `Expected Kubelet plugin watcher to create parent dir *dirname* but did not find such a dir` or something more eloquent
