### ISSUE TITLE
Option to tag PD with cluster name

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#469]
Since the driver is usually deployed per cluster, the cluster name could be passed in as a driver arg. This can help associate PDs to clusters. Instead of being specific to cluster name, it could also just take in a set of global tags. This is what ebs driver does.

/kind feature

**Comment by mattcary** [comment]
Is this effectively a duplicate of #340?

**Comment by msau42** [comment]
#340 is at the StorageClass level. This is at the cluster-level and could be automatically inferred by the provider that's deploying the driver.

**Comment by mattcary** [comment]
Got it, so it eg could be done at the same time that we set the PV info, https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/common/parameters.go#L86

**Comment by msau42** [comment]
Yeah it can be set when you create the PV, but the actual config could be set when you start the driver (as a driver arg)

**Comment by loganmzz** [comment]
I don't see interest in pushing explicitly cluster name into GCP-managed resources since cluster labels are already applied as describe in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/340#issuecomment-543221858.

Just add a `gke-cluster-id` (or similar) label(s) to your cluster. However, being able to distinct resources coming from a single cluster is still required. For the moment, I rely on `description` field which contains JSON structure. But as it's stored as raw string, filtering against is fragile.

Output example:

```
$ gcloud compute disks describe --zone gke-my-k8s-cluster-1bcec-pvc-a80c2aa5-f0c9-4a64-b3c4-a3930f037528
...
description: '{"kubernetes.io/created-for/pv/name":"pvc-a80c2aa5-f0c9-4a64-b3c4-a3930f037528","kubernetes.io/created-for/pvc/name":"my-k8s-pvc","kubernetes.io/created-for/pvc/namespace":"my-k8s-namespace"}'
...

**Comment by msau42** [comment]
There is this change here which is using Disk labels, and we'll have to do a followup to set the pvc/pv tags as a Label as well: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/566

As for cluster id as a label, it's useful for non-gke users.
