### ISSUE TITLE
Master logs missing in PDCSI e2e test runs

### ISSUE THREAD

**Issue by saikat-royc** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#594]
Seeing error like in the build.log file

{"msg":"PASSED External Storage [Driver: csi-gcepd-sc-standard] [Testpattern: Dynamic PV (default fs)] subPath should verify container cannot write to subpath readonly volumes [Slow]","total":-1,"completed":2,"skipped":81,"failed":0}
Aug 26 15:36:32.411: INFO: Running AfterSuite actions on all nodes
Aug 26 15:41:49.848: INFO: Running AfterSuite actions on node 1
Aug 26 15:41:49.848: INFO: Dumping logs locally to: /logs/artifacts/sc-standard.yaml
Checking for custom logdump instances, if any
Sourcing kube-util.sh
Detecting project
Skeleton Provider: detect-project not implemented
Dumping logs from master locally to '/logs/artifacts/sc-standard.yaml'
KUBE_MASTER_IP: 
KUBE_MASTER: 
/tmp/gcp-pd-driver-tmp712606268/kubernetes/cluster/log-dump/log-dump.sh: line 343: MASTER_NAME: unbound variable
Aug 26 15:41:49.862: INFO: Error running cluster/log-dump/log-dump.sh: exit status 1

Looks to be a side effect of https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/565

**Comment by mattcary** [comment]
It's been happening since at least August 3, on 1.17 at least, which is as far back as our archived pull logs seem to go. The problem seems to be with the log dumping in k/k/tests/e2e, the diagnostic bit from build.log is:

Dumping logs from master locally to '/logs/artifacts'
KUBE_MASTER_IP: 
KUBE_MASTER: 
/tmp/gcp-pd-driver-tmp636485011/kubernetes/cluster/log-dump/log-dump.sh: line 343: MASTER_NAME: unbound variable
Aug  3 21:32:36.888: INFO: Error running cluster/log-dump/log-dump.sh: exit status 1

**Comment by mattcary** [comment]
Note that it's not clear if it's a problem in k/k/test/e2e, or a problem with how run-k8s-integration is calling the e2e tests (eg, it may not be defining MASTER_NAME or similarly)

**Comment by mattcary** [comment]
That job is running on GKE, no wonder e2e.test can't find the master logs. We'd need special plumbing to pull them out of the master.

/close
